name: Webscaper Automation
run-name: Setting my scraper on a daily schedule
on:
  [push]
 # schedule:
  # - cron: "30 6 * * *"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: execute py script # run file
        run: |
          python /home/runner/work/webscraper/webscraper/scrape.py

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
